#!/usr/bin/env bash

# If aircon is running kill it so it can be moved to the correct folder
if pgrep -x "aircon" > /dev/null
then
    pkill aircon
fi

# Setup help text file, build the app, and then move the executable to the users local bin
go run ./cmd/main.go setupHelp && go build -o aircon ./cmd/main.go && cp aircon ~/.local/bin/aircon
