#!/usr/bin/env bash

# If aircon is running kill it so it can be moved to the correct folder
if pgrep -x "aircon" > /dev/null
then
    pkill aircon
fi

go build -o aircon ./cmd/main.go && mv aircon ~/.local/bin/aircon
