#!/usr/bin/env bash

while [ "$#" -gt 0 ]; do
    curr=$1
    shift

    case "$curr" in
   "-inc-1")
       airconNumber=$(~/.local/bin/aircon status | awk '{print $1}' | sed s/{// | awk -F "." '{print $1}')
       airconNumber=$(( $airconNumber + 1 ))

       /home/yoni/.local/bin/aircon $airconNumber
       ;;
   "-dec-1")
       airconNumber=$(~/.local/bin/aircon status | awk '{print $1}' | sed s/{// | awk -F "." '{print $1}')
       airconNumber=$(( $airconNumber - 1 ))

       ~/.local/bin/aircon $airconNumber
       ;;
   "-change")
       airconNumber=$(echo "" | rofi -dmenu -p "Enter Temp > ")
       ~/.local/bin/aircon $airconNumber
       ;;
   "-sellect-fan")
       fanMode=$(echo "night
1
2
3
4
5" | rofi -dmenu -i -p '[ Sellect fan mode ]')
       ~/.local/bin/aircon fan-$fanMode
       ;;
    *) echo "Unavailable command... $curr"
    esac
done
